// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SellGold.Stock.Infrastructure.Data.Context;

#nullable disable

namespace SellGold.Stock.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SellGoldStockContext))]
    [Migration("20251211122042_AddEstoqueTablesUpdatesNew")]
    partial class AddEstoqueTablesUpdatesNew
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SellGold.Stock.Domain.Entities.Address", b =>
                {
                    b.Property<Guid>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("StockLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressId");

                    b.HasIndex("StockLocationId");

                    b.ToTable("Address", "dbo");
                });

            modelBuilder.Entity("SellGold.Stock.Domain.Entities.StockLocation", b =>
                {
                    b.Property<Guid>("StockLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StockLocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StockProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StockLocationId");

                    b.HasIndex("StockProductId");

                    b.ToTable("StockLocation", "dbo");
                });

            modelBuilder.Entity("SellGold.Stock.Domain.Entities.StockMovement", b =>
                {
                    b.Property<Guid>("StockMovementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AmountMovement")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateMovement")
                        .HasColumnType("datetime2");

                    b.Property<int>("MovementType")
                        .HasColumnType("int");

                    b.Property<string>("Observation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StockProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StockMovementId");

                    b.HasIndex("StockProductId");

                    b.ToTable("StockMovement", "dbo");
                });

            modelBuilder.Entity("SellGold.Stock.Domain.Entities.StockProduct", b =>
                {
                    b.Property<Guid>("StockProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentQuantity")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StockProductId");

                    b.ToTable("StockProduct", "dbo");
                });

            modelBuilder.Entity("SellGold.Stock.Domain.Entities.Address", b =>
                {
                    b.HasOne("SellGold.Stock.Domain.Entities.StockLocation", null)
                        .WithMany("Addresses")
                        .HasForeignKey("StockLocationId");
                });

            modelBuilder.Entity("SellGold.Stock.Domain.Entities.StockLocation", b =>
                {
                    b.HasOne("SellGold.Stock.Domain.Entities.StockProduct", null)
                        .WithMany("StockLocation")
                        .HasForeignKey("StockProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SellGold.Stock.Domain.Entities.StockMovement", b =>
                {
                    b.HasOne("SellGold.Stock.Domain.Entities.StockProduct", null)
                        .WithMany("StockMovement")
                        .HasForeignKey("StockProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SellGold.Stock.Domain.Entities.StockLocation", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("SellGold.Stock.Domain.Entities.StockProduct", b =>
                {
                    b.Navigation("StockLocation");

                    b.Navigation("StockMovement");
                });
#pragma warning restore 612, 618
        }
    }
}
