events { }

http {
    # Upstreams para as APIs
    upstream products_api {
        server sellgold-api-products:8080;
    }

    # Caso ative a API de Fornecedores
    upstream suppliers_api {
        server sellgold-api-suppliers:8082;
    }

    # Redireciona todo tráfego HTTP para HTTPS
    server {
        listen 80;
        server_name localhost;
        return 301 https://$host$request_uri;
    }

    # Servidor HTTPS
    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate     /etc/nginx/certs/nginx-selfsigned.crt;
        ssl_certificate_key /etc/nginx/certs/nginx-selfsigned.key;

        # Proxy para API de Produtos
        location /products/ {
            proxy_pass http://products_api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Proxy para API de Fornecedores (quando ativar)
        location /suppliers/ {
            proxy_pass http://suppliers_api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}