// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SellGold.Suppliers.Infrastructure.Data.Context;

#nullable disable

namespace SellGold.Suppliers.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SellGoldSuppliersContext))]
    partial class SellGoldSupplierContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SellGold.Suppliers.Domain.Entities.Supplier", b =>
                {
                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("CorporateName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StateRegistration")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TradeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SupplierId");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Email");

                    b.HasIndex("IsActive");

                    b.ToTable("Suppliers", (string)null);
                });

            modelBuilder.Entity("SellGold.Suppliers.Domain.Entities.Supplier", b =>
                {
                    b.OwnsMany("SellGold.Suppliers.Domain.ValueObjects.Address", "Addresses", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Location_City")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("StreetInfo_Street")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<Guid>("SupplierId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("AddressType");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("ZipCode");

                            b1.HasKey("Id");

                            b1.HasIndex("SupplierId");

                            b1.HasIndex("ZipCode");

                            b1.ToTable("SupplierAddresses", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SupplierId");

                            b1.OwnsOne("SellGold.Suppliers.Domain.ValueObjects.Place", "Location", b2 =>
                                {
                                    b2.Property<int>("AddressId")
                                        .HasColumnType("int");

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)")
                                        .HasColumnName("City");

                                    b2.Property<string>("Country")
                                        .IsRequired()
                                        .ValueGeneratedOnAdd()
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasDefaultValue("Brasil")
                                        .HasColumnName("Country");

                                    b2.Property<string>("District")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)")
                                        .HasColumnName("District");

                                    b2.Property<string>("State")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnName("State");

                                    b2.HasKey("AddressId");

                                    b2.ToTable("SupplierAddresses");

                                    b2.WithOwner()
                                        .HasForeignKey("AddressId");
                                });

                            b1.OwnsOne("SellGold.Suppliers.Domain.ValueObjects.StreetInfo", "StreetInfo", b2 =>
                                {
                                    b2.Property<int>("AddressId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Complement")
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)")
                                        .HasColumnName("Complement");

                                    b2.Property<string>("Number")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("nvarchar(20)")
                                        .HasColumnName("Number");

                                    b2.Property<string>("Street")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("nvarchar(200)")
                                        .HasColumnName("Street");

                                    b2.HasKey("AddressId");

                                    b2.ToTable("SupplierAddresses");

                                    b2.WithOwner()
                                        .HasForeignKey("AddressId");
                                });

                            b1.Navigation("Location")
                                .IsRequired();

                            b1.Navigation("StreetInfo")
                                .IsRequired();
                        });

                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
